services:
  update-notifier:
    image: update-notifier
    build:
      context: .
      dockerfile: UpdateNotifier/Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${TOKEN}
      - DISCORD_GUILD_ID=${GUILD_ID}
      - DATABASE_PATH=/data/app.db
      - LOGS_FOLDER=/data/logs
      - SELF_HOSTED=false # enables supporter features
      - RSS_UPDATE_INTERVAL=5 # in minutes
      - XF_USER=${XF_USER}
      - XF_SESSION=${XF_SESSION}
    volumes:
      - ./data:/data