// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpdateNotifier.Data;

#nullable disable

namespace UpdateNotifier.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261002000000_AddGameThumbnailUrl")]
    partial class AddGameThumbnailUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("UpdateNotifier.Data.Models.Account", b =>
                {
                    b.Property<ulong>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.Game", b =>
                {
                    b.Property<ulong>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.LinkCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("AccountId");

                    b.ToTable("LinkCodes");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.PendingNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Id");

                    b.ToTable("PendingNotifications");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.PrivilegedUser", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("PrivilegedUsers");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WatchlistEntry", b =>
                {
                    b.Property<ulong>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WebAccount", b =>
                {
                    b.Property<int>("WebAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("WebAccountId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("WebAccounts");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WebSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("AccountId");

                    b.ToTable("WebSessions");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.LinkCode", b =>
                {
                    b.HasOne("UpdateNotifier.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.User", b =>
                {
                    b.HasOne("UpdateNotifier.Data.Models.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("UpdateNotifier.Data.Models.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WatchlistEntry", b =>
                {
                    b.HasOne("UpdateNotifier.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpdateNotifier.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WebAccount", b =>
                {
                    b.HasOne("UpdateNotifier.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.WebSession", b =>
                {
                    b.HasOne("UpdateNotifier.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UpdateNotifier.Data.Models.Account", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
